### ISSUE TITLE
Showcase example: OutputBuilder::build panicks with ALSA device

### ISSUE THREAD

**Issue by Jerboas86** [orottier/web-audio-api-rs#1]
Running showcase example on ALSA device, OutputBuilder::build panicks

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendSpecific { err: BackendSpecificError { description: "ALSA function 'snd_pcm_hw_params_set_buffer_size' failed with error 'EINVAL: Invalid argument'" } }', src/io.rs:81:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1037:23
   4: web_audio_api::io::OutputBuilder::build
             at ./src/io.rs:64:22
   5: web_audio_api::context::AudioContext::new
             at ./src/context.rs:293:22
   6: showcase::main
             at ./examples/showcase.rs:7:19
   7: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
If i set BUFFER_SIZE to 256, the program doesn't panick anymore.

But another bug appears. An assertion fails in debug mode (underflow in release mode)

```rust
thread 'cpal_alsa_out' panicked at 'assertion failed: `(left == right)`
  left: `78`,
 right: `0`', src/graph.rs:117:9
```
I think due to [#495](https://github.com/RustAudio/cpal/issues/495) build_output_stream is not called at fixed rate on ALSA devices.

**Comment by orottier** [comment]
Thanks for the detailed report. I don't have any ALSA device here so this is very helpful.

I'll add a resampling step before writing out the audio to deal with varying buffer sizes.
And maybe try to fall back to a default backend config when the lowest buffer_sizes config fails.

**Comment by Jerboas86** [comment]
Would you accept PR ? 

I solve the first panic by fallback on `default_output_config `when `build_output_stream `failed.

I'm not sure what you mean by  "resampling step" ?

**Comment by orottier** [comment]
That's great, I'd love to have a look at your work.
A ring buffer should do indeed, or anything that cut and pastes leftover samples per render quantum
