### ISSUE TITLE
[TAUDIO]Audio Streams under Flutter and React Native

### ISSUE THREAD

**Issue by Larpoux** [orottier/web-audio-api-rs#108]
Hi everybody,

This is not an issue. Just an information.
We are now working on the port of the Web Audio API under flutter, react native and Microsoft MAUI.
We need for that a native implementation of the Web Audio API on several platforms : 
- iOS
- Android
- Linux (optional)
- MacOS (optional)
- Windows (optional)

We found two existing libraries which can be used : 
- [LabSound](https://github.com/LabSound/LabSound)
- [Orottier Web-Audio-API-rs](https://github.com/orottier/web-audio-api-rs)

![Banner](https://flutter-sound.canardoux.xyz/images/taudio-architecture.svg)

Your library seems very interesting. We appreciate that it is dependant on CPAL, and CPAL is dependant of OBOE.
This seems a good design.

Unfortunately we are not expert with Rust.
We will probably need a little help from you, to start.

Good luck for your library.

**Comment by Catsvilles** [comment]
@Larpoux Cool idea, will this be open source or closed source? There is already https://github.com/xioxin/lab_sound_flutter for flutter btw

**Comment by Larpoux** [comment]
Thank you for the link. I am going to look to this flutter plugin.
Our license is actually a big problem for us.
I insist heavily for a GPL project.
But I am very lonely with such a choice. My peers want all MIT

**Comment by Larpoux** [comment]
In fact I develop Plugin Libraries but I do not know what our developers do with those libraries.
An example could be someone who needs to playback directly from the microphone with an equalizer between the mic and the speaker. The latency must be very small for him/her.
Someone else wanted to draw the sound volume or the sound frequency during a playback.
Someone else wanted to draw a diagram from his/her sound offline (no latency issue, here).

But I am not really sure what they will do with our Flutter Plugin.
I just think that many people will find many great utilisations if we offer a way to process sounds thanks to the WebAudioAPI

**Comment by orottier** [comment]
> Now we must take an important decision

@Larpoux I realize that is a tough call to make. If there's anything we can do to make the choice for our library easier, let us know.
We are fully committed to build out and improve on our work. So definitely in a year or so we will have a stable, performant, versatile and user friendly audio library.
For your information we are submitting our project for the Web Audio Conference of 2022. We hope to collect some more feedback and collaborators over there

**Comment by Larpoux** [comment]
Thank you @orottier.
Actually, everybody working on the &tau;Dio project want to try using your library and prefer not using LabSound. 
If later we realize that WebAudioApi was not a good choice then it will be possible to change that dependence. 

We will certainly need your help. 
Personally I would love to contribute to WebAudioApi development, but : 
- I do not master Rust
- I have absolutely no knowledge about audio processing 
- I am not sure that I will have some time left after working on &tau;Dio

But perhaps I will be able to do some very little things. It seems that you are just two developers working hard on this project and I think this is a big responsibility.

**Comment by orottier** [comment]
That's great to hear.

Based on what you are saying, I believe the best way to contribute would be to try out some of the examples and play around a bit. We are really interested to hear what you run into and what you think we should make more clear/easier to use. You might also run into platform-specific issues, since we have limited availability of hardware for testing.

If you are a bit more comfortable with rust and the audio examples, you could

- improve docs and example usage
- have a look at our issue board for simple tickets
- try to build some real world application (like example/mic_playback.rs)

**Comment by Larpoux** [comment]
Hi everybody,
After a 2 years vacation I am back on Tau. Tau is a flutter plugin that is an interface to web-audio-api.rs

I had a very bad time to setup an environment development for both flutter and rust. But now I have a correct flutter plugin for web-audio-api.rs. Now everything is clean and I am able to run a flutter app under Xcode that uses your lib.

** AND I AM EVEN ABLE TO USE THE XCODE DEBUGGER ON AN IOS DEVICE FOR YOUR RUST CODE **

Today I am a very happy geek. I will let you know my advancement.

‘Note: @orottier : I am not sure if I must keep this issue open (this is not an issue but an information). And I am not sure that such a thread is just pollution.

**Comment by orottier** [comment]
Great to hear back from you and happy to hear everything is working out. Please let us know if you run into any issues later, of if you have any other exciting news to share.
This issue is already in Closed state so we can keep it here for further reference/discussion.
