### ISSUE TITLE
Enhancement: Rendering oscillator with wavetable synthesis

### ISSUE THREAD

**Issue by Jerboas86** [orottier/web-audio-api-rs#11]
The current implementation of `OscillatorRenderer` is based on transcendental function `sin()`.

An alternative implementation based on [wave table](https://en.wikipedia.org/wiki/Wavetable_synthesis) may lead to:
- Better performance
- No aliasing behavior for non limited bandwidth signal type like square, triangle, and sawtooth

The current implementation is non compliant due to aliasing behavior [(web audio spec)](https://www.w3.org/TR/webaudio/#:~:text=Mathematically%20speaking%2C%20a,a%20digital%20form.)

**Solution:**

i got already a prototype working for sine type.

May i pursue work into this direction ?

**Comment by orottier** [comment]
Hi @Jerboas86, sure I'd be very interested to see some work.

The full spec OscillatorNode is quite a complicated thing though. My current implementation does not handle frequency shifts well, and the detune param is not implemented either.

In any case, your work on wave tables will open the way for the node's `setPeriodicWave` functionality (currently not implemented)

**Comment by orottier** [comment]
Fixed with #15
