### ISSUE TITLE
Rustdoc

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#123]
More a question than an issue, I really like the layout of the doc here https://docs.rs/web-audio-api/latest/web_audio_api/ especially the left-side bar which I find very clear, do you know if there is any way to have the same layout locally when running `cargo doc --lib --open`?

Also, it would be handy to have the link to the doc in the Github right side bar, just bellow the small description

**Comment by orottier** [comment]
Mmm, good question. I don't know actually.
Maybe try asking over at users.rust-lang.org ?
