### ISSUE TITLE
Unable to stop microphone processing

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#126]
The `Microphone` struct has pause/resume functionality (and will stop when dropped).
But how we intend to use it,

```rust
let context = AudioContext::new(None);
let stream = Microphone::new();
// register as media element in the audio context
let background = context.create_media_stream_source(stream);
// connect the node to the destination node (speakers)
background.connect(&context.destination());
```

ownership is given to the MediaStreamAudioSourceNode, which cannot be stopped.
So even when you disconnect the node, it will never drop as it will have tailTime true (this is contrary to the spec actually, I should dig into that).

A solution would be similar how we treat MediaStreamAudioDestinationNode:

```rust
let context = AudioContext::new(None);
let mic = Microphone::new();
let stream = mic.stream();
// register as media element in the audio context
let background = context.create_media_stream_source(stream);
// connect the node to the destination node (speakers)
background.connect(&context.destination());

// mic is still available now, so can be stopped/paused
// when mic Drops, it will stop automatically
```

This will have some caveats
- users should not Drop the Mic when playback is still desired
- you should not call `.stream()` multiple times
- it's quite different from the JS equivalent (it was already).

**Comment by orottier** [comment]
Assiging milestone v1 as it warrants a breaking API change. We could still accept the current limitations though

**Comment by b-ma** [comment]
For information, we will start a new prototype in few weeks where we plan to use the node bindings and the microphone, so I should be able to give (more) real-world feedback at this moment
