### ISSUE TITLE
Reconsider `sample_rate` type

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#152]
Currently, sample rates are implemented as a type safe `u32` wrapper:
`pub struct SampleRate(pub u32);`

This has a few advantages:
- u32 cannot be negative
- perfect representation of all integers up to 4B
- no confusion with other quantities (timestamp: f64, signal: f32, etc)

The spec mandates `f32` though - https://www.w3.org/TR/webaudio/#dom-baseaudiocontext-samplerate
Should we go with the spec here?
Integers between 0 and 16,777,216 can be exactly represented with 32 bit floats, which should be fine for sample rates

**Comment by b-ma** [comment]
`f32` !

I agree this type is bit weird, but this is the actual spec. I really think it will simplify / clean a lot of things (removing `sample_rate_raw()`, etc.) and as we have to `assert_valid_sample_rate()` in any case this is quite safe I guess.

Just wondering, type aliasing (https://doc.rust-lang.org/reference/items/type-aliases.html) could be an alternative or there is no real point to do that in our case ?

**Comment by orottier** [comment]
Alright, I will pick that up.

To me, type aliases are nice for code readability inside the library, but they do not provide much benefit for the users of the library. It's just another layer of indirection with no added safety

**Comment by orottier** [comment]
Fixed with #160
