### ISSUE TITLE
Sounds stop after a few seconds on Raspberry Pi

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#173]
Pretty weird things actually happen on Raspberry Pi, after a while (few seconds in general), the render thread goes to 100% and the sound just stops.

I started to investigate:
- benchmarks looks ok (expect for the granular, all benches are faster than real-time with quite decent number), which seems to show that the problem is lower-level and related to the audio thread
- created an idiot test bed, actually just an empty `AudioContext` with no nodes and the problem still occurs
I saw that `RenderThread::render` is called with buffers of 64 samples (sometime really weird numbers but always ratio of 64 at the end), while it should be 256 for stereo and the config given to `cpal` looks good. In any case, I guess there are some intertwined problems here because even if there is an issue with `cpal`, it doesn't really explain why the render thread seems to go into an infinite loop...

I will continue to investigate on that... e.g. try to use `Jack` instead of pure alsa as a backend to see if it makes things better

Any ideas welcome :)

**Comment by orottier** [comment]
Interesting, how does the memory usage progress over time?

**Comment by b-ma** [comment]
It's like normal, and at one point goes straight to 100% (as far as I can tell with htop)

Actually things seems to be due to the buffer size 128, if I increase it (e.g. to 512) things start to get real better. I even managed to run the granular example ! (will run it at lunch time to see how it behaves for a longer period)

I will also try with jack (or maybe pipewire) see if its related to alsa

**Comment by orottier** [comment]
Okay that is good. A lower sample rate might also alleviate the problem (but won't fix it!)

**Comment by b-ma** [comment]
hum, I was a bit optimistic... 512 also crash... I will try all increasing values one by one

> A lower sample rate might also alleviate the problem (but won't fix it!)

Yup, but actually when it runs, it does not take that much cpu (I'm quite impressed on that point), I really think it's more an alsa / cpal issue

**Comment by b-ma** [comment]
1024 worked for 2 hours without any drop!

**Comment by b-ma** [comment]
I think we can close this one as the problem appears to be solved when using at least `AudioContextLatencyCategory::Playback` (1024 samples, i.e. ~20ms of latency at 48kHz) or even larger latency values with `AudioContextLatencyCategory::Custom`.
