### ISSUE TITLE
How to deal with subnormal floats?

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#194]
> FYI this branch breaks SIMD-optimizations.

Damned !

> I'm wondering if this check (and the one we just added to the AudioParam) is worth it. We are slowing down all architectures to save some performance on exotic ones?

I'm afraid they are not really exotic platforms... Intel x86_64 just like mine... ARMv8 feels more exotic to me :)

I will remove that from the GainNode for now, maybe it's best to open an issue to make sure we don't forget the possible problem and wait until we both better understand it and (hopefully) have a better solution to propose

I wouldn't compare this with the check in the AudioParam that just happen once in a while in very specific conditions though

https://stackoverflow.com/questions/9314534/why-does-changing-0-1f-to-0-slow-down-performance-by-10x/9314926#9314926, there is also a comment about audio application there

_Originally posted by @b-ma in https://github.com/orottier/web-audio-api-rs/pull/191#discussion_r937352505_

**Comment by orottier** [comment]
I'm hoping we can do something on the compiler level. A hint is provided here: https://gist.github.com/GabrielMajeri/545042ee4f956d5b2141105eb6a505a9
But that is limited to some SIMD operations

**Comment by b-ma** [comment]
Yep, I saw this one too. But reading other threads it seems it may not be a really good idea to do that within a library as the whole final application would inherit the behaviour which may not be desirable...

From what I understand (but I'm really not sure there, this has to be confirmed) with fast math operations, this would be avoided too but these are still nightly, e.g. https://doc.rust-lang.org/std/intrinsics/fn.fmul_fast.html.

**Comment by orottier** [comment]
https://github.com/Sin-tel/no_denormals looks very useful
