### ISSUE TITLE
Support all AudioParam automation methods

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#20]
File: `param.rs`
Relevant section in spec: https://webaudio.github.io/web-audio-api/#AudioParam

#### Implement automation methods

- [x] SetValueAtTime
- [x] LinearRampToValueAtTime
- [x] ExponentialRampToValueAtTime
- [x] SetTargetAtTime
- [x] SetValueCurveAtTime
- [x] CancelScheduledValues
- [x] CancelAndHoldAtTime

#### Improvements / Spec

- [x] **spec** - All `panic` calls should be replaced by clean and compliant `Errors`
- [x] **spec** - Automation methods should return `self` or `Result(self, Error)` to allow method chaining
- [x] **spec** - Sanity check all method arguments (e.g. `times`, `time_constant`)
- [ ] ~~**refactoring** - Review all `AudioNode::new` to remove `set_value` or `set_value_at_time`, default values should be properly initialised at instantiation without calling an automation method explicitly~~ _(this is maybe a bad idea as it would create a confusion between the param default value and user defined default value)_
- [ ] **perf** - `set_target_at_time` can run forever as it as no "real" end time or value, a possible performance improvement would be to internally cancel the event when `intrisic_value` is close enough to the `target` (note that Chrome implements such strategy)

#### To be discussed further

- Maintain `AutomationEventQueue` in control thread instead of audio thread (e.g. `Arc<Mutex<AutomationEventQueue>>`?) - _is maybe necessary for proper Error handling_ (cf. discussion in [https://github.com/orottier/web-audio-api-rs/pull/62#discussion_r764294272](https://github.com/orottier/web-audio-api-rs/pull/62#discussion_r764294272)
- Possibly review `set_value_curve_at_time` signature to use `Vec<32>` instead of `&[f32]` (cf. discussion in [https://github.com/orottier/web-audio-api-rs/pull/62#discussion_r764292652](https://github.com/orottier/web-audio-api-rs/pull/62#discussion_r764292652))

**Comment by b-ma** [comment]
Hey, just to let you know that I've started to work on this one, if ok for you let me know if prefer a PR per item

**Comment by orottier** [comment]
Sure, go ahead! Let me warn you in advance the current setup may not be ideal for SetTargetAtTime so feel free to change the whole architecture. Also, I think only A-rate is properly tested with the existing implementation so some bugs may appear

**Comment by b-ma** [comment]
Hey, I have started to have a look at `CancelScheduledValues` but the following problem appeared: it seems that the only way to remove items from `events: BinaryHeap<AutomationEvent>` is to use the `retain` method which is still experimental (cf. [https://doc.rust-lang.org/stable/std/collections/struct.BinaryHeap.html#method.retain](https://doc.rust-lang.org/stable/std/collections/struct.BinaryHeap.html#method.retain)).

This seems to lead to the following options:
- Go on with the `BinaryHeap`, but requires to build using rust-nightly
- Change the type of the event queue to use a simple`Vec`, which will be of course a bit less efficient
- Or use another higher-level type such as [https://docs.rs/priority-queue/1.2.1/priority_queue/priority_queue/struct.PriorityQueue.html](https://docs.rs/priority-queue/1.2.1/priority_queue/priority_queue/struct.PriorityQueue.html) (which seems to allow removing arbitrary items)?

I would personally go for the `Vec` solution, as from my point of view such queue rarely contains hundreds of events, but this probably depends of the usage and use-cases too...

Do you have any opinion, ideas or preferred way on that point?

**Comment by orottier** [comment]
Is the `clear()` function not sufficient? 
In any case I would rather not switch to nightly.
Vec indeed sounds good. As the documentation of the BinaryHeap says, inserts of already sorted items is inefficient, which is probably the most common use case in this API

**Comment by b-ma** [comment]
> Is the clear() function not sufficient?

No, because we need to filter events according to `cancelTime`

> In any case I would rather not switch to nightly.
> Vec indeed sounds good. As the documentation of the BinaryHeap says, inserts of already sorted items is inefficient, which is probably the most common use case in this API

Ok thanks, I have made a simple wrapper around `Vec` with an API similar to the `BinaryHeap`, so that reverting or changing it later should be quite easy.

**Comment by orottier** [comment]
4 down, 3 to go!

**Comment by b-ma** [comment]
I will close this one and open new issues for the 2 points left:
- `set_target_at_time` limit check
- `AutomationEventQueue` in control thread
