### ISSUE TITLE
Add ConvolverNode

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#21]
https://webaudio.github.io/web-audio-api/#ConvolverNode

**Comment by Jerboas86** [comment]
I've got a direct form implementation ready for this one. 
But the state of the art is to mix direct form and FFT to obtain both good latency and computation efficiency. 
I can push a PR with the direct form alg or try to write the DF+FFT alg but it will require more time.

**Comment by orottier** [comment]
Hi @Jerboas86, you are still assigned this issue. Are you interested in publishing your direct form implementation?

**Comment by orottier** [comment]
To be continued with #220
