### ISSUE TITLE
Concat'ing audio

### ISSUE THREAD

**Issue by SorenHolstHansen** [orottier/web-audio-api-rs#214]
I am trying to concatenate two AudioBuffers. I saw this snippet from the [Crunker javascript library](https://github.com/jaggad/crunker) using the web audio API
```
function concatAudio(buffers: AudioBuffer[]): AudioBuffer {
    const output = this._context.createBuffer(
      this._maxNumberOfChannels(buffers),
      this._totalLength(buffers),
      this._sampleRate
    );
    let offset = 0;

    buffers.forEach((buffer) => {
      for (let channelNumber = 0; channelNumber < buffer.numberOfChannels; channelNumber++) {
        output.getChannelData(channelNumber).set(buffer.getChannelData(channelNumber), offset);
      }

      offset += buffer.length;
    });

    return output;
  }
```
and thought I would do sort of the same. However, they use `.set` on the `getChannelData` output, which works in js, but `getChannelData` returns a readonly value in rust. How would you do it in rust?

I am sorry if this is the wrong place to ask this question

**Comment by b-ma** [comment]
> I am sorry if this is the wrong place to ask this question

No problem, that's probably the right (maybe the only?) place to ask the question :)

More seriously, the choice of `get_channel_data` returning a read-only value was kind of a bet because the spec is not very clear on what should happen there and we didn't come up with any use case where this could be a problem. But the use case you have tends to demonstrate that this bet was maybe not the good one... I'm not sure right now if there is a simple answer or solution to that but that's certainly a good question

**Comment by orottier** [comment]
You should be able to do this with https://docs.rs/web-audio-api/latest/web_audio_api/struct.AudioBuffer.html#method.copy_to_channel_with_offset
I can whip up some example code later today, on mobile now

**Comment by orottier** [comment]
Hi @SorenHolstHansen, this is a port of the method you provided:

```
fn concat(buffers: &[AudioBuffer]) -> AudioBuffer {
    let number_of_channels = buffers
        .iter()
        .map(|b| b.number_of_channels())
        .max()
        .unwrap_or(1);
    let length = buffers.iter().map(|b| b.length()).sum();
    let sample_rate = buffers
        .iter()
        .next() // assuming all sample rates equal
        .map(|b| b.sample_rate())
        .unwrap_or(44_000.);

    let mut output = AudioBuffer::new(AudioBufferOptions {
        number_of_channels,
        length,
        sample_rate,
    });

    let mut offset = 0;
    for buffer in buffers {
        for c in 0..buffer.number_of_channels() {
            output.copy_to_channel_with_offset(buffer.get_channel_data(c), c, offset);
        }

        offset += buffer.length();
    }

    output
}
```

I believe the JS snippet is a bit dangerous. According to the spec
> According to the rules described in [acquire the content](https://www.w3.org/TR/webaudio/#acquire-the-content) either [get a reference to](https://heycam.github.io/webidl/#dfn-get-buffer-source-reference) or [get a copy of](https://heycam.github.io/webidl/#dfn-get-buffer-source-copy) the bytes stored in [[[internal data]]](https://www.w3.org/TR/webaudio/#dom-audiobuffer-internal-data-slot) in a new [Float32Array](https://heycam.github.io/webidl/#idl-Float32Array)

In practise it will just work fine, but in theory you could get a copy of the data in the output buffer, and setting any values to it will not have an effect on the actual output buffer

**Comment by b-ma** [comment]
Yup, I was just thinking about such kind of solution too :) I really agree `copy_to_channel` seems more clean and safe

**Comment by SorenHolstHansen** [comment]
Thanks a lot for this!
