### ISSUE TITLE
termion does not support windows

### ISSUE THREAD

**Issue by tasogare3710** [orottier/web-audio-api-rs#266]
This dependency causes many cargo subcommands to fail on windows.

**Comment by orottier** [comment]
Hey @tasogare3710, thanks for flagging.

Termion is only necessary for the `mic_playback` example and the `benchmarks` example.
I could move `mic_playback` into a different crate. That means we can drop the `simplelog` and `textplots` dependencies as well.

@b-ma what do you think about `benchmarks`? We could drop the interactivity right? And only leave the measurements? Or do you see value in the playback options in that file? In that case we could rewrite it to not use termion

**Comment by b-ma** [comment]
> @b-ma what do you think about benchmarks? We could drop the interactivity right? And only leave the measurements? Or do you see value in the playback options in that file? In that case we could rewrite it to not use termion

I think it is actually quite handy to be able to ear the results (already helped me to spot huge problems while working on the perfs), maybe this could be simplified to only use `std::io` such as you did in the `sink_id` example?
