### ISSUE TITLE
Gracefully fallback to default if given `sinkId` or `deviceId` does not exists

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#272]
Not sure how we want these to behave, to be discussed:

For output selection (`AudioContext` and `sinkId`), if the required `sinkId` is wrong, we get the following error message `NotFoundError: invalid sinkId "coucou"`

For input selection (`getUserMedia` and `deviceId`), if the required `deviceId` is wrong we have the following, and quite cryptic, error message: `called Option::unwrap() on a None value`

In both cases, it seems that Chrome and Firefox fallback to default device (Chrome additionally add a log in the console)

**Comment by orottier** [comment]
Logging and using a default seems sane to me. I can build that
