### ISSUE TITLE
Issue with mic input on linux (raspberry-pi)

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#281]
Hey,

I made some tests with the microphone on the Raspberry Pi with JACK backend and the fact is that we have an issue. For a reason I'm not sure how to explain, after a certain amount of time (from few seconds to few minutes depending of the Jack server block size) the mic audio stream just outputs zeros...

I tried to test the underlying libraries ([rust-jack](https://github.com/RustAudio/rust-jack) and [cpal](https://github.com/RustAudio/cpal)) and their example seem to work quite well (...still need to test for a longer time though).

But looking at the `cpal` example code (https://github.com/RustAudio/cpal/blob/master/examples/feedback.rs), I saw that they manually add some latency. I think it is to take into account that their API is not really duplex, which I guess implies that it's not possible to make sure the input is called before the output (?)
I tested with a latency of 3ms (around 1 block size) and it seems to work quite fine. So I wonder if we shouldn't add some double-buffering strategy to the input stream (maybe just for the Jack backend, it doesn't seems to be an issue on mac, and on other linux backend the buffer size is so large that it's not possible to do anything real-time anyway...)

What do you think? I can have a shot on that (I don't know if you can access some linux machine) see where it goes but I'm not completely sure where I should start?

**Comment by orottier** [comment]
Interesting. In theory our mic implementation should not fail catastrophically when the input callback lags behind the output.
Could you run it again with more logging? `RUST_LOG=debug cargo run --release --example microphone`
It should print a message when it drops buffers.

The relevant code part is 
https://github.com/orottier/web-audio-api-rs/blob/5c73c3a0411aff3e505155c44baea577fd9f05bd/src/io/cpal.rs#L254 we set up a channel with max 3 items in flight of 128 samples
https://github.com/orottier/web-audio-api-rs/blob/5c73c3a0411aff3e505155c44baea577fd9f05bd/src/io/microphone.rs#L102 when the input callback runs too fast, we drop the new frames
https://github.com/orottier/web-audio-api-rs/blob/5c73c3a0411aff3e505155c44baea577fd9f05bd/src/io/microphone.rs#L50 when the output callback runs too fast, we emit a chunk of silence, but after that we should pick up the stream again.

I now notice the log statement at https://github.com/orottier/web-audio-api-rs/blob/5c73c3a0411aff3e505155c44baea577fd9f05bd/src/io/microphone.rs#L50 is commented out, could you put it back when you run the example with more logging?

I do have an Ubuntu machine available but I would have to dust it off before testing myself
