### ISSUE TITLE
Choppy and heavily distorted output

### ISSUE THREAD

**Issue by uklotzde** [orottier/web-audio-api-rs#288]
On Fedora 38 none of the examples produces a clean output. The output is always choppy and heavily distorted, even if ALSA does not report any buffer underruns.

I noticed that the results vary on different runs. A clean run followed by a completely distorted run is possible. The distorted output even continues after the executable has terminated.

In contrast the cpal examples work as expected.

What am I missing? Why do even the simple examples do not work out of the box on a common platform?

**Comment by orottier** [comment]
(obligatory question, are you running in `--release` mode?)

Thanks for letting us know. I don't have an ALSA device myself so it's a bit hard to look into myself.

We have had an issue in the past where we would end up with pathetic settings for ALSA #28 
It would be helpful if you could run any example with debug logging and share the output so we know the actual audio output settings, e.g. with
`RUST_LOG=debug cargo run --release --example mono`

**Comment by b-ma** [comment]
From my testing on Raspberry Pi (so not fedora..), Alsa was really misbehaving with a block size lower than 1024 samples.
A simple way to test if you run in the same issue would be to use the `Playback` latency category:

```rs
let audio_context = AudioContext::new(AudioContextOptions {
    latency_hint: AudioContextLatencyCategory::Playback,
    ..AudioContextOptions::default()
});
```

**Comment by uklotzde** [comment]
@b-ma Thanks for the hint. A custom buffer size of 256 works with only very few and infrequent `ALSA lib pcm.c:8675:(snd_pcm_recover) underrun occurred` errors.

**Comment by orottier** [comment]
Thanks @uklotzde @b-ma .

If our issues with ALSA are more widespread than just the RPi, we should take some action because this is not exactly a warm welcome for new users trying out our library.

I propose we first limit ALSA to a render quantum size of at least 256 samples.
Next we could check if these issues also arise when using `--features cubeb` instead of `cpal`.
Then I could dig in further on a virtual device running ALSA to see what is actually happening, but this will take some more time and I'm not sure if I have the expertise.

**Comment by uklotzde** [comment]
Using cubeb is even worse. No sound at all and an assertion triggered on the first run:

```
[uk@nbookuk web-audio-api-rs]$ RUST_LOG=debug cargo run --features cubeb --example mono
   Compiling web-audio-api v0.30.0 (/home/uk/github/rust/web-audio-api-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 5.26s
     Running `target/debug/examples/mono`
[2023-06-18T11:20:34Z INFO  web_audio_api::io::cubeb] Audio Output Host: cubeb "pulse"
stream state changed: Started
stream state changed: Error
mono: /home/uk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cubeb-sys-0.10.3/libcubeb/src/cubeb_pulse.c:262: trigger_user_callback: Assertion `nbytes % frame_size == 0' failed.
Aborted (core dumped)
[uk@nbookuk web-audio-api-rs]$ RUST_LOG=debug cargo run --features cubeb --example mono
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/mono`
[2023-06-18T11:21:01Z INFO  web_audio_api::io::cubeb] Audio Output Host: cubeb "pulse"
stream state changed: Started
stream state changed: Error
stereo
mono
stereo
Segmentation fault (core dumped)
```

**Comment by uklotzde** [comment]
The assertion with cubeb occurs spuriously.

**Comment by b-ma** [comment]
>If our issues with ALSA are more widespread than just the RPi, we should take some action because this is not exactly a  warm welcome for new users trying out our library.

> I propose we first limit ALSA to a render quantum size of at least 256 samples.

I'm not sure that's the right way to go, as ALSA with a 256 block size will also break on some platforms anyway. If you want to do real-time / interactive audio on Linux you will have to rely on another backend such as Jack in any case. I would thus consider this more an application problem (in many applications having a large buffer is really not an issue)... but it doesn't solve the example question for new users...

Maybe an in between solution would be to document the ALSA problem more clearly in the README and to provide a flag to run the examples with the `latency_hint: AudioContextLatencyCategory::Playback` (e.g. something like `cargo run --release --example my_example -- --playback`) which works fine on RPis so we can hope it should work quite well on any computer used by a developer trying the library :) It wouldn't hurt too much the readability of the examples while also give developers a hint that the default block size is quite low, which may not be what they need
