### ISSUE TITLE
Add channelCount Constraints to ChannelConfigOptions

### ISSUE THREAD

**Issue by Jerboas86** [orottier/web-audio-api-rs#29]
Channel configuration is constrained for some node [(more details in the specs)](https://www.w3.org/TR/webaudio/#:~:text=In%20addition%2C%20some%20nodes%20have%20additional%20channelCount%20constraints%20on%20the%20possible%20values%20for%20the%20channel%20count%3A). I run into this  problem trying to implement ConvolverNode api. 

Currently, theses constraints seems not implemented.

I think the most compliant implementation would be to panic when building the constrained node. Another solution would be to catch the constraints in the type system. What do you think ?

**Comment by orottier** [comment]
This was fixed in #130 by overriding the `set_channel_count/mode/interpretation` function on concrete AudioNode types, panicing when constraints are not met.
