### ISSUE TITLE
Make AudioBuffer more compliant

### ISSUE THREAD

**Issue by Jerboas86** [orottier/web-audio-api-rs#30]
There is some differences between Rust AudioBuffer API and Web audio specs AudioBuffer API. [(see specs for more details)](https://www.w3.org/TR/webaudio/#audiobuffer)

Possible solution:
- Replace current implementation with the following interface `AudioBuffer::sample_rate(&self) -> f32`
- Rename `sample_len()` function as `length()`
- Rename `channel_data` function as `get_channel_data`
- Rename `channel_data_mut` function as `get_channel_data_mut`
- Make `from_channels` function private and add a public `copy_to_channel` function
- Add a public `copy_from_channel` function

There is this concept of "acquire the content" in the spec [(see specs for more details)](https://www.w3.org/TR/webaudio/#acquire-the-content). I think it could be emulate by using systematically move semantics with AudioBuffer. What do you think ?
If yes, it should be documented

**Comment by b-ma** [comment]
- `buffer::ChannelData` should be `pub(crate)`, but is currently used in `examples/bench.rs`
- would also allow to move `buffer::AudioBuffer::from<DataChannel>` to `pub(crate)` once done

**Comment by orottier** [comment]
Fixed with #67
