### ISSUE TITLE
Rewrite audio nodes to use proper message passing instead of atomics

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#315]
Continuation from the initial work of #311 , these nodes still need changes:

- [x] BiquadFilterNode
- [x] ConvolverNode
- [x] PannerNode
- [x] WaveShaperNode

For further consideration
- [ ]  also rewrite the ChannelConfig to use message passing

**Comment by b-ma** [comment]
Actually about https://github.com/orottier/web-audio-api-rs/pull/329, I think I will just remove the new `LoopControl` struct as there is finally no `Arc`, anything on your sides against that?

**Comment by orottier** [comment]
Fixed with #337
