### ISSUE TITLE
Issue with graph initialization

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#331]
Hey, 

I quite often have this error with the node bindings (don't remember having seen this in raw rust, but I'm less using it so I'm not sure):

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value',  /web-audio-api-0.32.0/src/render/graph.rs:479:14
```

Just like if the graph is rendered before the `AudioDestination` is created 

Any idea where it could come from?

**Comment by b-ma** [comment]
> As I mentioned earlier, booting the audio thread on OSX takes about 60 milliseconds, so I wonder what your control thread is doing in the meantime.

My guess is that the JS bindings kind of amplify stuff that we don't really see with raw Rust because of how JS works. For example, I'm more and more thinking that deallocation + GC creates issues that we can't really see with just raw Rust (just like putting you trash out every day or... "sometimes" :)

> In any case I could have a look if I can change the ordering of the control messages for initialization to prevent this from ever happening.

Cool, I can also have a look if you prefer to focus on other things, but any hint would be welcome!

**Comment by orottier** [comment]
Fixed in https://github.com/orottier/web-audio-api-rs/pull/338
