### ISSUE TITLE
Add AudioContextOptions to AudioContext constructor

### ISSUE THREAD

**Issue by Jerboas86** [orottier/web-audio-api-rs#35]
In the specs, we can build `audioContext` with an optional argument [`AudioContextOptions`](https://www.w3.org/TR/webaudio/#dictdef-audiocontextoptions)

```js
dictionary AudioContextOptions {
  (AudioContextLatencyCategory or double) latencyHint = "interactive";
  float sampleRate;
};
```

I think we should extend this options like that:

```js
dictionary AudioContextOptions {
  (AudioContextLatencyCategory or double) latencyHint = "interactive";
  float sampleRate;
  unsigned long channels = 2;
};
```
This way, the user can specify the number of output channels that it would like. The current behavior is that the user has only access to default configuration given by CPAL.

Should `AudioContext::new(options: Option<AudioContextOptions>)` be fallible ?

My opinion is that it should not. The method should fallback to CPAL default config if user requested config fails.
And provides supported config as an error message.

related to #28 
related to #32

**Comment by orottier** [comment]
Closed with merging #36
