### ISSUE TITLE
Implement `AudioContext::onstatechange`

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#408]
https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-onstatechange

I was trying to experiment with the event bindings stuff and got quite surprised it was actually not already implemented. 
Should be quite straightforward isn't it?

**Comment by orottier** [comment]
Yup. Also see #219 but a separate issue is maybe better. A simple implementation can be made but regard:
> onstatechange for BaseAudioContext (needs some work because state changes are 'instant' now but should signal device readiness)

**Comment by b-ma** [comment]
> onstatechange for BaseAudioContext (needs some work because state changes are 'instant' now but should signal device readiness)

Maybe I'm missing something here, but as `resume`, `suspend` and `close` are synchronous for now this shouldn't be issue?

**Comment by orottier** [comment]
They are synchronous in the sense that they don't return a promise, but I'm afraid `cpal` just asks the render thread to suspend/close/resume and returns immediately. So depending on how accurate we want to be in spawning the event, it could mean some extra work on our end.

For example, we could suspend by
- send a control message to pause processing to the audio graph
- when the render thread processes this message, stop emitting audio and dispatch the onstatechange event
- when the control thread encounters the onstatechange, actually ask cpal to suspend the audio thread

But maybe I'm overcomplicating stuff. I could start with the naive approach

**Comment by b-ma** [comment]
>  I could start with the naive approach

Yup, we can always recheck that later with a more robust version
