### ISSUE TITLE
channel_count constraint of get_user_media_sync is not supported

### ISSUE THREAD

**Issue by trevorparscal** [orottier/web-audio-api-rs#446]
I would like to suggest adding support for more than 2 channels for media streams. The WebAudio spec does include this in the form of specifying channelCount in the constraints.

At first I [noted](https://github.com/ircam-ismm/node-web-audio-api/issues/74) that this JavaScript wrapper for web-audio-api-rs didn't support it. But then I realized this is a feature request for the underlying rust implementation.

Here's a basic test case...

```Rust
use web_audio_api::context::AudioContext;
use web_audio_api::media_devices::{self, MediaTrackConstraints};
use web_audio_api::media_devices::MediaStreamConstraints;
use web_audio_api::node::AudioNode;

fn main() {
	let context = AudioContext::default();

	let devices = media_devices::enumerate_devices_sync();
	for device in devices.iter() {
		println!( "{}", device.label() );

		let mut media_track_constraints = MediaTrackConstraints::default();
		media_track_constraints.device_id = Some( device.device_id().to_string() );

		// Ideally, this would be supported
		// media_track_constraints.channel_count = Some( 18 );

		let input = media_devices::get_user_media_sync(
			MediaStreamConstraints::AudioWithConstraints( media_track_constraints )
		);
		let stream = context.create_media_stream_source(&input);

		println!( "> {}", stream.channel_count() );
	}
}

```
Hopefully this could be added in the near future.

**Comment by orottier** [comment]
Thanks for the report. This feature should not be too hard too add, I can have a look at it this week.

The pesky thing is that `media_track_constraints.channel_count: Option<u32>` is actually not spec compliant, we need to find a way to model the https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#constrainulong

But perhaps we can deal with that later. We don't intend to fully implement the Media Devices API here anyway.
