### ISSUE TITLE
Free audio processor resources when the node will never start processing

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#462]
For `AudioScheduledSourceNode`, renderer should be dropped when control side has been dropped and the source has not been started (it cannot be started anyway)

**Comment by orottier** [comment]
Yep, good one. Easier to implement than https://github.com/orottier/web-audio-api-rs/issues/397
Wondering if we could fix this easily by responding `tail_time = false` when a start time has not been set..

Looking at can_free that looks alright. BTW I should rename `free_when_finished` to `control_handle_dropped`

```
    /// Determine if this node is done playing and can be removed from the audio graph
    fn can_free(&self, tail_time: bool) -> bool {
        // Only drop when the Control thread has dropped its handle.
        // Otherwise the node can be reconnected/restarted etc.
        if !self.free_when_finished {
            return false;
        }

        // Drop when the node does not have any inputs and outputs
        if !self.has_inputs_connected && self.outgoing_edges.is_empty() {
            return true;
        }

        // Drop when the node does not have any inputs connected,
        // and if the processor reports it won't yield output.
        if !self.has_inputs_connected && !tail_time {
            return true;
        }

        // Otherwise, do not drop the node.
        // (Even if it has no outputs connected, it may have side effects)
        false
    }
```

**Comment by b-ma** [comment]
> Wondering if we could fix this easily by responding tail_time = false when a start time has not been set..

Yup looks like a good idea indeed, don't see any potential weird side effects

> BTW I should rename free_when_finished to control_handle_dropped

+1
