### ISSUE TITLE
Suspended + Sound put windows apps into "Not Responding" state

### ISSUE THREAD

**Issue by ggadwa** [orottier/web-audio-api-rs#496]
This one I can actually easily recreate with a test!  Yes, this code is slop but it's just a test file I hack away at when I find something I need to test outside the confines of my very complicated game code.  The actual preproduction would probably be a lot simplier.

This one is easy -- is you suspend_sync() and then play a sound (it might take one or two) eventually a windows application will fall into "not responding" and lock up.  No processor time, BTW, just it locks up.  Could be some interaction with winit.  I found this on the rc.5 branch.

`use winit::{event::*, event_loop::{ControlFlow, EventLoop}, window::{Window, WindowBuilder}};
use web_audio_api::{context::{BaseAudioContext, AudioContext}, node::{AudioNode, AudioScheduledSourceNode, PanningModelType, DistanceModelType}};
use std::f32::consts::PI;
use std::time::Instant;

pub async fn run() {
    env_logger::init();

    let event_loop = EventLoop::new();
    let window =
        WindowBuilder::new()
            .with_title("blech")
            .with_inner_size(winit::dpi::LogicalSize::new(1024.0, 768.0))
            .with_resizable(false)
            .build(&event_loop).unwrap();

    // the audio context
    let ctx = AudioContext::default();

    // run the window loop
    event_loop.run(move |event, _, control_flow| {
        match event {
            Event::WindowEvent {
                ref event,
                window_id,
            } if window_id == window.id() => {
                match event {
                    WindowEvent::MouseInput {
                        button,
                        state,
                        ..
                    } => {
                        if *state==ElementState::Pressed {
                            println!("sound");

                            ctx.suspend_sync();

                            let length = ctx.sample_rate() as usize;
                            let sample_rate = ctx.sample_rate();
                            let mut src = ctx.create_buffer_source();
                            let flat_wave = vec![1.0; length];
                            let mut buffer = ctx.create_buffer(1, length, sample_rate);
                            buffer.copy_to_channel(&flat_wave, 0);
                            
                            src.set_buffer(buffer.clone());
                            src.set_loop(true);

                            let gain = ctx.create_gain();
                            gain.gain().set_value(1.0);

                            src.connect(&gain);
                            gain.connect(&ctx.destination());
                            src.start();

                        }
                    },
                    WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
                    _ => {}
                }
            }
            Event::RedrawRequested(window_id) if window_id == window.id() => {
            }
            Event::RedrawEventsCleared => {
                window.request_redraw();
            }
            _ => {}
        }
    });
}`

**Comment by orottier** [comment]
Hi @ggadwa. Thanks for another report, I really appreciate it.

I don't have a Windows machine laying around here so I can't run your code, but I can think of a possible cause.

Our library may block the control thread when the render thread cannot handle control messages fast enough. Control messages are actions like "add a new node", "start a node", "change a param value" etc.
The queue size of control messages is 256 items so in normal operations we can handle that many messages per render block (typically run every 3 milliseconds or so).
When the context is suspended, this may become an issue because we will block indefinitely after 256 new messages as the render thread handles zero messages in suspended state.
We don't use an unbounded (infinite size) channel because it can cause (de)allocations in the render thread which is a no go for latency considerations.

Now looking at your example code, it does not really seem like you are emitting this many control messages so maybe there is something else going on. Anyway I would like to rule out this scenario. So if you are okay with it, I will push a new branch (you know the drill) and I'm happy to hear the output.

**Comment by orottier** [comment]
I have pushed a branch called `feature/crash-on-full-channel`, it would be very helpful if you could run your code with it

**Comment by ggadwa** [comment]
Here you go!

[2024-04-17T19:33:04Z INFO  web_audio_api::io::cpal] Audio Output Host: cpal Wasapi
[2024-04-17T19:33:04Z INFO  web_audio_api::io::cpal] Output device: Ok("Speakers / Headphones (Realtek Audio)")
[2024-04-17T19:33:04Z DEBUG web_audio_api::io::cpal] Attempt output stream with preferred config: StreamConfig { channels: 2, sample_rate: SampleRate(48000), buffer_size: Fixed(128) }
[2024-04-17T19:33:04Z INFO  web_audio_api::render::thread] Entering garbage collector thread
[2024-04-17T19:33:04Z DEBUG web_audio_api::io::cpal] Output stream set up successfully
[2024-04-17T19:33:04Z DEBUG web_audio_api::events] Entering event thread
click
before suspend_sync
[2024-04-17T19:33:06Z DEBUG web_audio_api::context::online] suspend_sync called
[2024-04-17T19:33:06Z DEBUG web_audio_api::context::online] Supending audio graph, waiting for signal..
[2024-04-17T19:33:06Z DEBUG web_audio_api::context::online] Supended audio graph. Suspending audio stream..
[2024-04-17T19:33:06Z DEBUG web_audio_api::context::online] Supended audio stream
after suspend_sync
before make sound
after make sound
click
before suspend_sync
[2024-04-17T19:33:08Z DEBUG web_audio_api::context::online] suspend_sync called
[2024-04-17T19:33:08Z DEBUG web_audio_api::context::online] Supending audio graph, waiting for signal..
error: process didn't exit successfully: `target\release\webaudio_test.exe` (exit code: 0xcfffffff)

NOTES: I added the log items so you could see where it was.  It obviously goes into the suspend_sync on the 2nd click and never comes out again (the error is when I kill the app because it's frozen.)

So: (1) suspend (2) play sound (3) suspend (freeze)

So it is suspending an already suspended context, but that should probably be a no-op.

**Comment by orottier** [comment]
Ahh I see, we do not handle double suspend properly and end up blocking. This should be an easy fix (hopefully this week)

**Comment by ggadwa** [comment]
I know you know this, but while you are at it, make sure double resumes are no-ops, too, just in case!

Again, thanks for this great library.  When my game enters beta you can have a beta key!

**Comment by orottier** [comment]
> double resumes are no-ops

Thanks for the nudge. And I would be very interested in seeing your final product
