### ISSUE TITLE
Change sample rate type from SampleRate(u32) to SampleRate(f32)

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#50]
Which conforms to the spec: https://www.w3.org/TR/webaudio/#dom-baseaudiocontext-samplerate

I'd like to keep the newtype wrapper in place so we don't accidentally mix up a f32 sample_rate parameter with a f32 timestamp one. See related discussion https://github.com/orottier/web-audio-api-rs/pull/33#issuecomment-949365714

**Comment by b-ma** [comment]
Just to note, timestamps should probably be `f64`: [cf. https://www.w3.org/TR/webaudio/#dom-baseaudiocontext-currenttime](https://www.w3.org/TR/webaudio/#dom-baseaudiocontext-currenttime) (which make sens for long running applications)

**Comment by orottier** [comment]
Fixed in #80
