### ISSUE TITLE
Disable all dependencies for compilation-only test?

### ISSUE THREAD

**Issue by fzyzcjy** [orottier/web-audio-api-rs#513]
Hi thanks for the library! I am trying to make it a part of test of https://github.com/fzyzcjy/flutter_rust_bridge to test flutter_rust_bridge's ability of automatically scanning and converting third party crates. Therefore, it would be great if it is possible to disable all dependencies for compilation-only (and not to be really run) test.

**Comment by orottier** [comment]
Hey, thanks for the report, but I'm not sure I understand. You can't compile a rust crate without its dependencies.

We do offer the ability to use this crate without audio backend (disable the "cpal" feature) and without media decoder capabilities (the "mp3", "ogg", "flac", "wav", "m4a", "alac" features.

So compiling with `default-features = false` still leaves quite a few dependencies. You can use `cargo tree --no-default-features --edges no-dev` to inspect them.

Looking a those, I could also make `creek` and its transitive dependencies an optional feature (it is used for the HtmlMediaElement features) if that helps.

**Comment by fzyzcjy** [comment]
Yes that looks like what I need, thank you!
