### ISSUE TITLE
android context was not initializedBacktrace []

### ISSUE THREAD

**Issue by Larpoux** [orottier/web-audio-api-rs#520]
- When I use web-audio-api-rs on iOS, everything good.
- When I use it on Android I get immediately this error : 
```
android context was not initializedBacktrace []
```

I don't know if it is a problem with web-audio-api-rs, with cpal or with oboe

Please help : do I need to do something to initialize web-audio-api-rs for android ?

**Comment by orottier** [comment]
Thanks for flagging. I have no experience running this on Android myself so I don't think I can be of much help.
Perhaps you can try to run some of the cpal examples on Android and see if that gives the same issue?

**Comment by Larpoux** [comment]
I found some informations on this issue:
https://github.com/RustAudio/cpal/issues/720

It seems that it is an issue with CPAL, or perhaps Oboe.
He/she gives a solution to turn around the problem.
