### ISSUE TITLE
Finalize all node constructor structs (e.g. ConstantSourceOptions) 

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#73]
For the v1.0 release, structs with public fields must be finalized since altering them would mean a breaking API change.

- [ ] decide on types (f64 for all float values?)
- [ ] add all fields to all constructor structs, even if the implementation is not yet using them
- [ ] add all enum variants (e.g. PanningModelType) even if the implementation is not yet using them
- [ ] how to handle optional fields?
- [ ] add a Default, Clone and Debug implementation on all structs

**Comment by b-ma** [comment]
(will try to put my 2 cents in each issues)

For the type, my impression from the spec is that all that is related to time is `f64` (even if internally casted to f32, e.g. `delayTime`, and this is important to keep timing precision in long running applications), while every other values are more `f32` (and as the difference between `double` and `float` is already made, it is quite simple to follow without interpreting to much there). For count / enumerating attributes, (e.g. `channelCount`, `number_of_channels`), which are generally described as `unsigned long` I guess `usize` is generally the right one choice as these params / arguments are often used as indexes, etc.

**Comment by orottier** [comment]
This was fixed in #103 
Some leftover tasks are listed in #76
