### ISSUE TITLE
Hide unfinished functionality behind a `nightly` feature flag

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#74]
Some functionality was added but is subject to change. Let's introduce an opt-in `nightly` feature flag and make unstable functionality only available there.

- ~decodeAudioData~ (finished now)
- ~MediaElement~ (dropped for now)
- [x] public methods in src/spatial.rs
- [x] Resampler

**Comment by b-ma** [comment]
Another possibility, if really needed (cf. #78), would also be to hide the Node's constructors behind this flag (in JS, I think most of the time people use the `AudioContext` factory methods, I don't even think the constructors were available in Safari before the very latest versions).

**Comment by orottier** [comment]
Closing this issue.
I think we have fixed this by either finishing, marking private, or dropping (postponing) features
