### ISSUE TITLE
Decide how to deal with fallible operations (e.g. exceptions thrown)

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#75]
In the spec, exceptions are thrown all over the place (when creating nodes, when updating attributes, when calling methods..)

There a few options for the rust version:

- panic on exception (this is what we do currently)
- all fallible operations must return a `Result<..>`
- all operations must return a `Result<..>` (for consistency, even infallible ones)
- panic on exception but offer a `try_...` method for fallible operations returning a `Result`
- ignore errors (log them)

All variants have pros and cons. We need to strike a balance between correctness and pragmatism.

e.g. https://docs.rs/curl/0.4.41/curl/ returns a Result for every operation meaning your code will be littered with `unwrap`s

The rust stdlib strikes a reasonable balance between (well documented) panics and offering `try_...` functions, in my opinion (e.g. https://doc.rust-lang.org/std/cell/struct.RefCell.html#method.try_borrow )

**Comment by b-ma** [comment]
Tricky one... another point to take into account maybe is how often the fallible methods return a value you actually want to use use. For example, with params most of the time you will write something like:

```rs
my_param.set_value(0., 0.);
my_param.linear_ramp_to_value_at_time(1., 1.);
my_param.exponential_ramp_to_value_at_time(0.0001, 1.);
```

If we followed the spec here (returning `self` for method chaining) while handling `Error`s using `Result`, (if I'm not wrong here...) we could allow writing something like the following while still allowing the first snippet :

```rs
my_param
   .set_value(0., 0.)?
   .linear_ramp_to_value_at_time(1., 1.)?
   .my_param.exponential_ramp_to_value_at_time(0.0001, 1.)?;
```

I don't say that's the best solution at all (and I'm personally really not for the `unwrap()` everywhere solution), but would maybe be interesting to have a clear picture of all the actual fallible operations before having a decision that may have a lot of impact on the interface.

**Comment by orottier** [comment]
Current user facing panics:
- AudioParam: exponential_ramp_to_value_at_time, set_target_at_time (for bad numerical inputs)
- AudioBuffer: from (if channel have unequal len)
- AudioBufferSource (when setting buffer more than once, when starting/stopping more than once)
- WaveShaper (when setting curve more than once)
- AudioNode, when connecting nodes from different contexts. Note: connect_at returns a Result instead of panicing when ports are not available.
- DelayNode: when delay time is <0 or >180s
- ChannelSplitter/MergerNode: when overriding channel config

This makes me strongly in favour of *keeping the panics* and not returning `Results` now, for 3 reasons:
- these panics are rare and easily avoidable
- no need for all these `unwrap`s or `?`s (which would typically cause a panic anyway)
- over time, we can introduce `try_....` methods returning `Result`s if users request them, without causing a breaking change

One nitty detail: inside the render thread are some panics that could be caused by user input. That should be avoided at all cost. Notably inside the AudioParam computation, but I do not see a simple solution there (except for logging and ignoring). Not relevant for this issue, but something to look into later.

**Comment by b-ma** [comment]
About `AudioParam` panic in render thread, just 2 notes: 

- This one: `panic!("AudioParamEvent {:?} should not appear in AudioParamEventTimeline", event.event_type)`, is really for development purpose (maybe these another more semantic way of writing that), if the module works as expected this should never happen.
- The other ones are more related with the fact that we should probably maintain the event queue in the control thread (as discussed a bit in #20)

> This makes me strongly in favour of keeping the panics and not returning Results now,

I really agree with that, returning `Result`s could really spoil the development experience

**Comment by b-ma** [comment]
> "src/node/waveshaper.rs" line 170 which we should probably fix? Not sure what the intention is here?

Me neither actually maybe an error, I don't really see how this could happen at all

**Comment by orottier** [comment]
I think we are done for now.
Most panics are documented, and are easily avoidable so no real need for `Results`.
Whenever we start to implement the async methods (that return a Promise) we should take a new look since Promises have reject/failure built in
